### PR TITLE
Add Continuous integration

### PR DESCRIPTION
**Pull request by jdubois**
Create a Github Action to run continuous integration on Pull Requests

### CODE REVIEW

**Comment by jdubois** [comment]
This is both for us (so PRs have a small validation), and for people cloning it (so they have a working CI pipeline by default)

**Comment by chrmarti** [comment]
The action combines a few standard actions. Anyone cloning the repository might want to customize the sequence and parameters of these actions. It might make more sense to inline the standard actions it: https://github.com/microsoft/nubesgen-actions/blob/main/gitops-build-java-maven/action.yml.

**Comment by jdubois** [comment]
Oh yes the composite Action was to make it shorter, but I can copy/paste so we use the full steps.
Let me update the PR.

**Comment by jdubois** [comment]
I have removed the composite action @chrmarti @joshspicer

**Review by chrmarti — APPROVED** [review]
LGTM thanks!

**Pull request merged**
